import type { PracticeExam } from '../types';

export const awsCloudPractitionerExams: PracticeExam[] = [
  {
    id: 'exam-1',
    title: 'Practice Exam 1',
    description: "Full-length mixed practice across all CLF-C02 domains.",
    suggestedMinutes: 30,
    questions: [
      {
        id: 'e1q1',
        question: "Which of the following is a key financial benefit of moving from on-premises infrastructure to the AWS Cloud?",
        options: [
          { id: 'a', text: "Trading capital expense for variable expense", correct: true },
          { id: 'b', text: "Eliminating the need for any security controls", correct: false },
          { id: 'c', text: "Guaranteeing zero cost for all services", correct: false },
          { id: 'd', text: "Removing the ability to scale resources", correct: false },
        ],
        explanation: "A core benefit of cloud computing is trading capital expense (buying data centers and servers up front) for variable expense, where you pay only for the computing resources you consume.",
        topic: 'Cloud Concepts',
      },
      {
        id: 'e1q2',
        question: "What is the smallest unit of AWS global infrastructure that consists of one or more discrete data centers with redundant power and networking?",
        options: [
          { id: 'a', text: "Region", correct: false },
          { id: 'b', text: "Availability Zone", correct: true },
          { id: 'c', text: "Edge location", correct: false },
          { id: 'd', text: "Local Zone", correct: false },
        ],
        explanation: "An Availability Zone (AZ) consists of one or more discrete data centers with redundant power, networking, and connectivity. A Region is made up of multiple AZs.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e1q3',
        question: "Under the AWS shared responsibility model, which task is the responsibility of the customer?",
        options: [
          { id: 'a', text: "Maintaining the physical security of data centers", correct: false },
          { id: 'b', text: "Patching the hypervisor on host servers", correct: false },
          { id: 'c', text: "Configuring security groups and managing guest OS patches on EC2", correct: true },
          { id: 'd', text: "Replacing failed hardware components", correct: false },
        ],
        explanation: "AWS is responsible for security OF the cloud (physical infrastructure, hypervisor). The customer is responsible for security IN the cloud, including guest OS patching, security group configuration, and their data.",
        topic: 'Security & Compliance',
      },
      {
        id: 'e1q4',
        question: "Which AWS service provides on-demand access to AWS compliance reports and agreements such as SOC and PCI DSS?",
        options: [
          { id: 'a', text: "AWS Artifact", correct: true },
          { id: 'b', text: "AWS Config", correct: false },
          { id: 'c', text: "Amazon Inspector", correct: false },
          { id: 'd', text: "AWS Trusted Advisor", correct: false },
        ],
        explanation: "AWS Artifact is a self-service portal for on-demand access to AWS compliance reports and select online agreements, such as SOC reports and PCI DSS.",
        topic: 'Security & Compliance',
      },
      {
        id: 'e1q5',
        question: "A company wants to run code without provisioning or managing servers, paying only for compute time consumed. Which service should they use?",
        options: [
          { id: 'a', text: "Amazon EC2", correct: false },
          { id: 'b', text: "AWS Lambda", correct: true },
          { id: 'c', text: "Amazon Lightsail", correct: false },
          { id: 'd', text: "AWS Batch", correct: false },
        ],
        explanation: "AWS Lambda is a serverless compute service that runs code in response to events and automatically manages the underlying compute. You pay only for the compute time you consume.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e1q6',
        question: "Which Amazon storage service is designed for object storage with virtually unlimited scalability and 11 nines of durability?",
        options: [
          { id: 'a', text: "Amazon EBS", correct: false },
          { id: 'b', text: "Amazon EFS", correct: false },
          { id: 'c', text: "Amazon S3", correct: true },
          { id: 'd', text: "Amazon FSx", correct: false },
        ],
        explanation: "Amazon S3 is object storage built to store and retrieve any amount of data, offering 99.999999999% (11 nines) durability and virtually unlimited scalability.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e1q7',
        question: "Which pricing model offers the largest discount but can be interrupted by AWS with two minutes of notice?",
        options: [
          { id: 'a', text: "On-Demand Instances", correct: false },
          { id: 'b', text: "Reserved Instances", correct: false },
          { id: 'c', text: "Spot Instances", correct: true },
          { id: 'd', text: "Dedicated Hosts", correct: false },
        ],
        explanation: "Spot Instances let you use spare EC2 capacity at discounts of up to 90%, but AWS can reclaim them with a two-minute warning. They suit fault-tolerant, flexible workloads.",
        topic: 'Billing & Support',
      },
      {
        id: 'e1q8',
        question: "Which AWS support plan is the lowest tier that provides access to a Technical Account Manager (TAM)?",
        options: [
          { id: 'a', text: "Developer", correct: false },
          { id: 'b', text: "Business", correct: false },
          { id: 'c', text: "Enterprise On-Ramp", correct: false },
          { id: 'd', text: "Enterprise", correct: true },
        ],
        explanation: "A designated Technical Account Manager (TAM) is provided with the Enterprise Support plan. Enterprise On-Ramp offers a pool of TAMs but a dedicated/designated TAM is an Enterprise feature.",
        topic: 'Billing & Support',
      },
      {
        id: 'e1q9',
        question: "Which service helps protect web applications from common exploits such as SQL injection and cross-site scripting?",
        options: [
          { id: 'a', text: "AWS Shield", correct: false },
          { id: 'b', text: "AWS WAF", correct: true },
          { id: 'c', text: "Amazon GuardDuty", correct: false },
          { id: 'd', text: "Amazon Macie", correct: false },
        ],
        explanation: "AWS WAF (Web Application Firewall) lets you create rules to filter web traffic and protect against common exploits like SQL injection and cross-site scripting (XSS).",
        topic: 'Security & Compliance',
      },
      {
        id: 'e1q10',
        question: "Which two of the following are recommended best practices for securing the AWS account root user? (Choose TWO.)",
        options: [
          { id: 'a', text: "Enable multi-factor authentication (MFA) on the root user", correct: true },
          { id: 'b', text: "Use the root user for all daily administrative tasks", correct: false },
          { id: 'c', text: "Share the root credentials with the entire operations team", correct: false },
          { id: 'd', text: "Create individual IAM users for everyday access instead of using root", correct: true },
          { id: 'e', text: "Store the root password in the application source code", correct: false },
        ],
        explanation: "Best practices include enabling MFA on the root user and creating individual IAM users (or roles) for everyday tasks rather than using the powerful root account.",
        topic: 'Security & Compliance',
      },
      {
        id: 'e1q11',
        question: "Which AWS service records API calls and account activity for governance, compliance, and auditing?",
        options: [
          { id: 'a', text: "Amazon CloudWatch", correct: false },
          { id: 'b', text: "AWS CloudTrail", correct: true },
          { id: 'c', text: "AWS Config", correct: false },
          { id: 'd', text: "AWS CloudFormation", correct: false },
        ],
        explanation: "AWS CloudTrail records API calls and account activity, capturing who made a request, when, and from where. CloudWatch focuses on performance metrics and monitoring.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e1q12',
        question: "Which fully managed relational database service supports engines such as MySQL, PostgreSQL, and Oracle?",
        options: [
          { id: 'a', text: "Amazon DynamoDB", correct: false },
          { id: 'b', text: "Amazon RDS", correct: true },
          { id: 'c', text: "Amazon Redshift", correct: false },
          { id: 'd', text: "Amazon ElastiCache", correct: false },
        ],
        explanation: "Amazon RDS is a managed relational database service supporting multiple engines including MySQL, PostgreSQL, MariaDB, Oracle, and SQL Server. DynamoDB is NoSQL and Redshift is a data warehouse.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e1q13',
        question: "A company wants to distribute static and dynamic content to users worldwide with low latency using a global network of edge locations. Which service should they use?",
        options: [
          { id: 'a', text: "Amazon CloudFront", correct: true },
          { id: 'b', text: "AWS Direct Connect", correct: false },
          { id: 'c', text: "Amazon Route 53", correct: false },
          { id: 'd', text: "AWS Global Accelerator", correct: false },
        ],
        explanation: "Amazon CloudFront is a content delivery network (CDN) that caches content at edge locations around the world to deliver content to users with low latency.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e1q14',
        question: "Which tool lets you estimate the cost of an AWS architecture before deploying it?",
        options: [
          { id: 'a', text: "AWS Cost Explorer", correct: false },
          { id: 'b', text: "AWS Pricing Calculator", correct: true },
          { id: 'c', text: "AWS Budgets", correct: false },
          { id: 'd', text: "AWS Cost and Usage Report", correct: false },
        ],
        explanation: "The AWS Pricing Calculator lets you model and estimate the cost of AWS services and architectures before you build them. Cost Explorer analyzes actual past usage.",
        topic: 'Billing & Support',
      },
      {
        id: 'e1q15',
        question: "Which AWS service uses machine learning to automatically discover and classify sensitive data such as personally identifiable information (PII) in Amazon S3?",
        options: [
          { id: 'a', text: "Amazon Inspector", correct: false },
          { id: 'b', text: "Amazon Macie", correct: true },
          { id: 'c', text: "Amazon GuardDuty", correct: false },
          { id: 'd', text: "AWS KMS", correct: false },
        ],
        explanation: "Amazon Macie uses machine learning and pattern matching to discover, classify, and protect sensitive data such as PII stored in Amazon S3.",
        topic: 'Security & Compliance',
      },
      {
        id: 'e1q16',
        question: "Which feature of AWS Organizations lets you apply permission guardrails across multiple accounts to restrict what actions can be performed?",
        options: [
          { id: 'a', text: "IAM policies", correct: false },
          { id: 'b', text: "Service Control Policies (SCPs)", correct: true },
          { id: 'c', text: "Security groups", correct: false },
          { id: 'd', text: "Network ACLs", correct: false },
        ],
        explanation: "Service Control Policies (SCPs) in AWS Organizations set the maximum available permissions (guardrails) for accounts within the organization, restricting what member accounts can do.",
        topic: 'Security & Compliance',
      },
      {
        id: 'e1q17',
        question: "Which pillar of the AWS Well-Architected Framework focuses on the ability of a system to recover from failures and meet demand?",
        options: [
          { id: 'a', text: "Cost Optimization", correct: false },
          { id: 'b', text: "Reliability", correct: true },
          { id: 'c', text: "Performance Efficiency", correct: false },
          { id: 'd', text: "Operational Excellence", correct: false },
        ],
        explanation: "The Reliability pillar focuses on ensuring a workload performs its intended function correctly and consistently, and can recover quickly from failures and meet demand.",
        topic: 'Cloud Concepts',
      },
      {
        id: 'e1q18',
        question: "What is the primary benefit of consolidated billing in AWS Organizations?",
        options: [
          { id: 'a', text: "It provides one bill for all accounts and enables volume pricing discounts across them", correct: true },
          { id: 'b', text: "It eliminates all charges for member accounts", correct: false },
          { id: 'c', text: "It prevents member accounts from launching resources", correct: false },
          { id: 'd', text: "It automatically encrypts all data at rest", correct: false },
        ],
        explanation: "Consolidated billing provides a single bill for all accounts in an organization and aggregates usage so accounts can share volume pricing discounts and Reserved Instance benefits.",
        topic: 'Billing & Support',
      },
      {
        id: 'e1q19',
        question: "Which two services are used for application decoupling and messaging in AWS? (Choose TWO.)",
        options: [
          { id: 'a', text: "Amazon SQS", correct: true },
          { id: 'b', text: "Amazon SNS", correct: true },
          { id: 'c', text: "Amazon EBS", correct: false },
          { id: 'd', text: "Amazon Redshift", correct: false },
          { id: 'e', text: "AWS Direct Connect", correct: false },
        ],
        explanation: "Amazon SQS (a managed message queue) and Amazon SNS (a pub/sub notification service) are used to decouple and coordinate the components of distributed applications.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e1q20',
        question: "Which characteristic best describes the cloud computing benefit of elasticity?",
        options: [
          { id: 'a', text: "The ability to scale resources up or down automatically to match demand", correct: true },
          { id: 'b', text: "The guarantee that all services are free of charge", correct: false },
          { id: 'c', text: "The requirement to purchase hardware in advance", correct: false },
          { id: 'd', text: "The inability to change resource capacity once provisioned", correct: false },
        ],
        explanation: "Elasticity is the ability to acquire resources as you need them and release them when you no longer need them, scaling automatically to match demand.",
        topic: 'Cloud Concepts',
      },
    ],
  },
  {
    id: 'exam-2',
    title: 'Practice Exam 2',
    description: "A second set of fresh questions — no repeats from Exam 1.",
    suggestedMinutes: 30,
    questions: [
      {
        id: 'e2q1',
        question: "Which cloud deployment model describes running some workloads on-premises while others run in the AWS Cloud, with connectivity between them?",
        options: [
          { id: 'a', text: "Public cloud", correct: false },
          { id: 'b', text: "Hybrid cloud", correct: true },
          { id: 'c', text: "Private cloud", correct: false },
          { id: 'd', text: "Multi-region cloud", correct: false },
        ],
        explanation: "A hybrid deployment connects cloud-based resources to on-premises infrastructure, allowing workloads to run in both environments with connectivity between them.",
        topic: 'Cloud Concepts',
      },
      {
        id: 'e2q2',
        question: "Which AWS service continuously monitors for malicious activity and unauthorized behavior using threat intelligence and machine learning?",
        options: [
          { id: 'a', text: "Amazon GuardDuty", correct: true },
          { id: 'b', text: "AWS WAF", correct: false },
          { id: 'c', text: "AWS Artifact", correct: false },
          { id: 'd', text: "Amazon Inspector", correct: false },
        ],
        explanation: "Amazon GuardDuty is a threat detection service that continuously monitors accounts and workloads for malicious activity using machine learning and threat intelligence feeds.",
        topic: 'Security & Compliance',
      },
      {
        id: 'e2q3',
        question: "Which AWS service automatically assesses applications for software vulnerabilities and unintended network exposure?",
        options: [
          { id: 'a', text: "Amazon Macie", correct: false },
          { id: 'b', text: "Amazon Inspector", correct: true },
          { id: 'c', text: "AWS Shield", correct: false },
          { id: 'd', text: "AWS Config", correct: false },
        ],
        explanation: "Amazon Inspector is an automated vulnerability management service that scans EC2 instances and container images for software vulnerabilities and unintended network exposure.",
        topic: 'Security & Compliance',
      },
      {
        id: 'e2q4',
        question: "A developer needs a managed NoSQL database that delivers single-digit millisecond performance at any scale. Which service is the best fit?",
        options: [
          { id: 'a', text: "Amazon RDS", correct: false },
          { id: 'b', text: "Amazon Aurora", correct: false },
          { id: 'c', text: "Amazon DynamoDB", correct: true },
          { id: 'd', text: "Amazon Redshift", correct: false },
        ],
        explanation: "Amazon DynamoDB is a fully managed key-value and document NoSQL database that delivers consistent single-digit millisecond performance at virtually any scale.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e2q5',
        question: "Which service allows you to deploy and manage web applications by simply uploading code, while it handles provisioning, load balancing, and scaling?",
        options: [
          { id: 'a', text: "AWS Elastic Beanstalk", correct: true },
          { id: 'b', text: "AWS CloudFormation", correct: false },
          { id: 'c', text: "Amazon EC2", correct: false },
          { id: 'd', text: "AWS Lambda", correct: false },
        ],
        explanation: "AWS Elastic Beanstalk is a Platform as a Service that lets you upload application code while it automatically handles capacity provisioning, load balancing, scaling, and health monitoring.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e2q6',
        question: "Which storage class in Amazon S3 is designed for long-term archival at the lowest cost, with retrieval times of minutes to hours?",
        options: [
          { id: 'a', text: "S3 Standard", correct: false },
          { id: 'b', text: "S3 Intelligent-Tiering", correct: false },
          { id: 'c', text: "S3 Glacier Deep Archive", correct: true },
          { id: 'd', text: "S3 Standard-IA", correct: false },
        ],
        explanation: "S3 Glacier Deep Archive is the lowest-cost S3 storage class, designed for long-term archival of data that is rarely accessed, with retrieval times of hours.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e2q7',
        question: "Which AWS service provides a logically isolated section of the AWS Cloud where you can launch resources in a virtual network you define?",
        options: [
          { id: 'a', text: "Amazon VPC", correct: true },
          { id: 'b', text: "Amazon Route 53", correct: false },
          { id: 'c', text: "AWS Direct Connect", correct: false },
          { id: 'd', text: "Amazon CloudFront", correct: false },
        ],
        explanation: "Amazon VPC (Virtual Private Cloud) lets you provision a logically isolated section of the AWS Cloud where you launch resources in a virtual network with full control over IP ranges, subnets, and routing.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e2q8',
        question: "Which AWS tool provides real-time guidance and recommendations across categories like cost optimization, security, and fault tolerance?",
        options: [
          { id: 'a', text: "AWS Trusted Advisor", correct: true },
          { id: 'b', text: "AWS CloudTrail", correct: false },
          { id: 'c', text: "Amazon CloudWatch", correct: false },
          { id: 'd', text: "AWS Config", correct: false },
        ],
        explanation: "AWS Trusted Advisor inspects your environment and provides recommendations across five categories: cost optimization, performance, security, fault tolerance, and service limits.",
        topic: 'Billing & Support',
      },
      {
        id: 'e2q9',
        question: "Which two IAM entities can be assigned permissions through policies in AWS? (Choose TWO.)",
        options: [
          { id: 'a', text: "IAM roles", correct: true },
          { id: 'b', text: "IAM users", correct: true },
          { id: 'c', text: "Availability Zones", correct: false },
          { id: 'd', text: "Edge locations", correct: false },
          { id: 'e', text: "S3 buckets", correct: false },
        ],
        explanation: "IAM policies can be attached to IAM users, groups, and roles to grant permissions. Roles are assumed by trusted entities and users represent individual identities.",
        topic: 'Security & Compliance',
      },
      {
        id: 'e2q10',
        question: "Which service manages the creation and control of encryption keys used to encrypt data across AWS services?",
        options: [
          { id: 'a', text: "AWS KMS", correct: true },
          { id: 'b', text: "AWS Artifact", correct: false },
          { id: 'c', text: "Amazon Macie", correct: false },
          { id: 'd', text: "AWS WAF", correct: false },
        ],
        explanation: "AWS Key Management Service (KMS) makes it easy to create and control the cryptographic keys used to encrypt your data, integrating with many AWS services.",
        topic: 'Security & Compliance',
      },
      {
        id: 'e2q11',
        question: "Which service lets you set custom cost and usage thresholds and receive alerts when they are exceeded or forecasted to be exceeded?",
        options: [
          { id: 'a', text: "AWS Budgets", correct: true },
          { id: 'b', text: "AWS Pricing Calculator", correct: false },
          { id: 'c', text: "AWS Cost and Usage Report", correct: false },
          { id: 'd', text: "AWS Organizations", correct: false },
        ],
        explanation: "AWS Budgets lets you set custom budgets for cost or usage and receive alerts when actual or forecasted amounts exceed your defined thresholds.",
        topic: 'Billing & Support',
      },
      {
        id: 'e2q12',
        question: "Which AWS service provides a managed data warehouse optimized for running complex analytical queries against large datasets?",
        options: [
          { id: 'a', text: "Amazon Redshift", correct: true },
          { id: 'b', text: "Amazon DynamoDB", correct: false },
          { id: 'c', text: "Amazon RDS", correct: false },
          { id: 'd', text: "Amazon ElastiCache", correct: false },
        ],
        explanation: "Amazon Redshift is a fully managed, petabyte-scale data warehouse service optimized for online analytical processing (OLAP) and complex queries against large datasets.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e2q13',
        question: "Which service provides a highly available and scalable Domain Name System (DNS) web service?",
        options: [
          { id: 'a', text: "Amazon Route 53", correct: true },
          { id: 'b', text: "Amazon CloudFront", correct: false },
          { id: 'c', text: "Elastic Load Balancing", correct: false },
          { id: 'd', text: "Amazon VPC", correct: false },
        ],
        explanation: "Amazon Route 53 is a highly available and scalable DNS web service that routes end users to applications by translating domain names into IP addresses.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e2q14',
        question: "Which compute option lets you run containers without having to provision or manage the underlying servers?",
        options: [
          { id: 'a', text: "AWS Fargate", correct: true },
          { id: 'b', text: "Amazon EC2", correct: false },
          { id: 'c', text: "AWS Elastic Beanstalk", correct: false },
          { id: 'd', text: "Amazon Lightsail", correct: false },
        ],
        explanation: "AWS Fargate is a serverless compute engine for containers that works with Amazon ECS and EKS, removing the need to provision and manage EC2 servers.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e2q15',
        question: "A company has a steady, predictable workload and wants to reduce EC2 costs by committing to a consistent amount of usage for a one- or three-year term. Which options are appropriate? (Choose TWO.)",
        options: [
          { id: 'a', text: "Reserved Instances", correct: true },
          { id: 'b', text: "Savings Plans", correct: true },
          { id: 'c', text: "Spot Instances", correct: false },
          { id: 'd', text: "On-Demand Instances", correct: false },
          { id: 'e', text: "Dedicated Hosts billed hourly on-demand", correct: false },
        ],
        explanation: "Both Reserved Instances and Savings Plans offer significant discounts in exchange for a one- or three-year usage commitment, making them ideal for steady, predictable workloads.",
        topic: 'Billing & Support',
      },
      {
        id: 'e2q16',
        question: "Which service enables you to define your AWS infrastructure as code using templates so environments can be provisioned repeatably?",
        options: [
          { id: 'a', text: "AWS CloudFormation", correct: true },
          { id: 'b', text: "AWS CloudTrail", correct: false },
          { id: 'c', text: "Amazon CloudWatch", correct: false },
          { id: 'd', text: "AWS Config", correct: false },
        ],
        explanation: "AWS CloudFormation lets you model and provision AWS resources using templates (infrastructure as code), enabling consistent and repeatable deployments.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e2q17',
        question: "Which block storage service provides persistent volumes that attach to a single Amazon EC2 instance?",
        options: [
          { id: 'a', text: "Amazon EBS", correct: true },
          { id: 'b', text: "Amazon S3", correct: false },
          { id: 'c', text: "Amazon EFS", correct: false },
          { id: 'd', text: "Amazon Glacier", correct: false },
        ],
        explanation: "Amazon EBS (Elastic Block Store) provides persistent block-level storage volumes that attach to EC2 instances. EFS is a shared file system that can attach to many instances.",
        topic: 'Cloud Technology & Services',
      },
      {
        id: 'e2q18',
        question: "Which AWS Support plan provides 24x7 access to Cloud Support Engineers via phone, chat, and email, and is the lowest tier to do so?",
        options: [
          { id: 'a', text: "Basic", correct: false },
          { id: 'b', text: "Developer", correct: false },
          { id: 'c', text: "Business", correct: true },
          { id: 'd', text: "Enterprise", correct: false },
        ],
        explanation: "The Business Support plan is the lowest tier offering 24x7 access to Cloud Support Engineers by phone, chat, and email. Developer provides business-hours email access to support only.",
        topic: 'Billing & Support',
      },
      {
        id: 'e2q19',
        question: "Which service protects AWS workloads against Distributed Denial of Service (DDoS) attacks, with a Standard tier enabled automatically at no extra cost?",
        options: [
          { id: 'a', text: "AWS Shield", correct: true },
          { id: 'b', text: "AWS WAF", correct: false },
          { id: 'c', text: "Amazon GuardDuty", correct: false },
          { id: 'd', text: "AWS Firewall Manager", correct: false },
        ],
        explanation: "AWS Shield provides DDoS protection. Shield Standard is automatically enabled for all AWS customers at no additional cost, while Shield Advanced offers enhanced protection for a fee.",
        topic: 'Security & Compliance',
      },
      {
        id: 'e2q20',
        question: "What does the AWS Free Tier primarily allow new customers to do?",
        options: [
          { id: 'a', text: "Explore and try out AWS services free of charge within certain usage limits", correct: true },
          { id: 'b', text: "Use all AWS services for free indefinitely with no limits", correct: false },
          { id: 'c', text: "Receive a full refund of all charges after one year", correct: false },
          { id: 'd', text: "Access dedicated hardware at no cost", correct: false },
        ],
        explanation: "The AWS Free Tier lets customers gain free hands-on experience with AWS services within specified usage limits, through always-free, 12-month free, and short-term trial offers.",
        topic: 'Billing & Support',
      },
    ],
  },
];
